dubbo:
  protocol:
    name: dubbo
    port: 20880
    payload: 8388608
    serialization: hessian2
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: demo.provider.api
server:
  port: 8081
logging:
  root: debug
spring:
  application:
    name: server